services:
  - type: static
    name: tape-input-app
    env: static
    buildCommand: cd tape-s && npm install && npm run build
    staticPublishPath: tape-s/dist
    routes:
      - path: /*
        destination: /index.html
